### ISSUE TITLE
Add personal tracking to now

### ISSUE THREAD

**Issue by deblnia** [deblnia/deblnia.github.io#33]
- [ ]  books (goodreads) 
- [ ] github contrib 
- [ ] steps
- [X] new words 
- [ ] weight?
- [ ] crossword 
- [ ] keybr typing speed 
- [ ] leetcode 
- [ ] project euler 
- [ ] weather 
- [x] Erdos Number (should be Erdos (4): Deblina Mukherjee > James Evans > Nathan Srebro > Noga Alon > Paul Erdos)
- [ ] Page visits (make sure to rip out google analytics too) 
- [ ] Flights
- [ ] Books
- [ ] Movies

**Comment by deblnia** [comment]
Github is done but this was pre-built.
